version: '3.3'

services:
  postgres:
    build: backend/postgres-dev/
    command: postgres -p 5432
    ports:
    - 5432:5432
    volumes:
    - ./backend/db_data/:/var/lib/postgresql/db_data
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB_LIST: $POSTGRES_DATABASE_LIST
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  todolist:
    build: backend/todolist
    command: sh ./docker-entrypoint.sh
    volumes: 
    - ./backend/todolist/:/app
    restart: always
    ports:
    - 5050:5050
    environment: 
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: $COPYRIGHT_DB

      FLASK_APP: wsgi.py
      FLASK_ENV: development