"""Initial Revision

Revision ID: 88e208a9b196
Revises: 
Create Date: 2021-03-04 11:09:33.690274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e208a9b196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('list_item_id', sa.Integer(), nullable=False),
    sa.Column('todo_content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('list_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_list')
    # ### end Alembic commands ###
