"""test revision

Revision ID: 9a59f0921487
Revises: 88e208a9b196
Create Date: 2021-03-04 11:22:25.128690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a59f0921487'
down_revision = '88e208a9b196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_list', 'todo_content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_list', 'todo_content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
